event(
  id: 16,
  name: "Remove follower size(1,4)",
  x: 1,
  y: 17,
  page_0: page(
    trigger: :player_touch,
    commands: [
      *comment(
        "This event removes a follower (May) and moves it to ",
        "a particular position. It only triggers if the player has ",
        "moved left onto this event, and only if they have a ",
        "follower. Note that this event is 4 tiles tall, covering ",
        "the whole path.",
      ),
      *comment(
        "These trigger requirements let us know exactly where ",
        "the follower will be in relation to the player, which is ",
        "information we can use below to ensure the correct ",
        "move route is given to the follower to make it end up ",
        "in the correct position.",
      ),
      *condition(
        script: "$game_player.has_follower?",
        then: condition(
          character: player,
          facing: :left,
          then: [
            comment("Turn the player towards the follower while it talks."),
            *move_route(
              player,
              turn_right,
            ),
            *comment(
              "Make the follower show an exclamation bubble. The ",
              "script here means that the next Show Animation ",
              "command will play over the follower instead of ",
              "whatever target it says it applies to.",
            ),
            script("follower_animation"),
            show_animation(this, anim(3)),
            wait(10),
            text("\\rI'll wait here, then."),
            *comment(
              "This line of code means that the next Set Move Route ",
              "command will apply to the follower, rather than to the ",
              "event/player it says it applies to. Only one Set Move ",
              "Route command is reassigned by the use of this ",
              "code.",
            ),
            script("follower_move_route"),
            *comment(
              "Give the follower a different move route depending ",
              "on where the player currently is, to ensure it ends up ",
              "at the correct position. Note that Through is set ON ",
              "because the follower will be moved into the tile ",
              "occupied by the event it will be replaced with.",
            ),
            control_variables(v(1), character: player, property: :map_y),
            *condition(
              variable: v(1),
              operation: "==",
              constant: 14,
              then: [
                *move_route(
                  this,
                  through_on,
                  move_down,
                  move_right,
                  turn_down,
                  through_off,
                  skippable: true,
                ),
              ],
            ),
            *condition(
              variable: v(1),
              operation: "==",
              constant: 15,
              then: [
                *move_route(
                  this,
                  through_on,
                  move_right,
                  turn_down,
                  through_off,
                  skippable: true,
                ),
              ],
            ),
            *condition(
              variable: v(1),
              operation: "==",
              constant: 16,
              then: [
                *move_route(
                  this,
                  through_on,
                  move_up,
                  move_right,
                  turn_down,
                  through_off,
                  skippable: true,
                ),
              ],
            ),
            *condition(
              variable: v(1),
              operation: "==",
              constant: 17,
              then: [
                *move_route(
                  this,
                  through_on,
                  move_up,
                  move_up,
                  move_right,
                  turn_down,
                  through_off,
                  skippable: true,
                ),
              ],
            ),
            comment("Wait for the follower to finish moving."),
            wait_completion,
            *comment(
              "Once the follower has finished moving, remove it as a ",
              "follower. At the same time, turn event 44's Self ",
              "Switch A on, which depicts May.",
            ),
            script("Followers.remove(\"May\")"),
            script("pbSetSelfSwitch(44, \"A\", true)"),
            comment("Deregister the trainer."),
            script("pbDeregisterPartner"),
          ],
        ),
      ),
    ],
  ),
)