event(
  id: 2,
  name: "Controls",
  x: 0,
  y: 2,
  page_0: page(
    commands: [
      *comment(
        "Ask the player which the floor they want to go to, ",
        "and store it in Game Variable 11.",
        "The difference between this and the current floor (in ",
        "Game Variable 10) determines which wall animation is ",
        "played, as well as how many times it is played.",
      ),
      text("Which floor do you want?"),
      *show_choices(
        choices: ["5F", "4F", "3F"],
        cancellation: 0,
        choice1: [
          control_variables(v(11), constant: 5),
        ],
        choice2: [
          control_variables(v(11), constant: 4),
        ],
        choice3: [
          control_variables(v(11), constant: 3),
        ],
      ),
      *show_choices(
        choices: ["2F", "1F", "Cancel"],
        cancellation: 3,
        choice1: [
          control_variables(v(11), constant: 2),
        ],
        choice2: [
          control_variables(v(11), constant: 1),
        ],
        choice3: [
          exit_event_processing,
        ],
      ),
      *comment(
        "Exit this event immediately if the destination floor is ",
        "the current floor.",
      ),
      *condition(
        variable: v(11),
        operation: "==",
        other_variable: v(10),
        then: [
          exit_event_processing,
        ],
      ),
      comment("Animate the elevator moving to the new floor."),
      play_se(audio(name: "Elevator moving", volume: 80)),
      label("Start"),
      *condition(
        variable: v(11),
        operation: ">",
        other_variable: v(10),
        then: [
          comment("Go up."),
          screen_shake(power: 4, speed: 9, frames: 12),
          *move_route(
            character(3),
            turn_left,
            route_wait(2),
            turn_right,
            route_wait(2),
            turn_down,
            route_wait(2),
            turn_left,
            route_wait(2),
            turn_right,
            route_wait(2),
            turn_down,
            route_wait(2),
          ),
          *move_route(
            character(4),
            turn_left,
            route_wait(2),
            turn_right,
            route_wait(2),
            turn_down,
            route_wait(2),
            turn_left,
            route_wait(2),
            turn_right,
            route_wait(2),
            turn_down,
            route_wait(2),
          ),
          *move_route(
            character(5),
            turn_left,
            route_wait(2),
            turn_right,
            route_wait(2),
            turn_down,
            route_wait(2),
            turn_left,
            route_wait(2),
            turn_right,
            route_wait(2),
            turn_down,
            route_wait(2),
          ),
          wait_completion,
          control_variables(v(10), "+=", constant: 1),
          jump_label("Start"),
        ],
      ),
      *condition(
        variable: v(11),
        operation: "<",
        other_variable: v(10),
        then: [
          comment("Go down."),
          screen_shake(power: 4, speed: 9, frames: 12),
          *move_route(
            character(3),
            turn_right,
            route_wait(2),
            turn_left,
            route_wait(2),
            turn_down,
            route_wait(2),
            turn_right,
            route_wait(2),
            turn_left,
            route_wait(2),
            turn_down,
            route_wait(2),
          ),
          *move_route(
            character(4),
            turn_right,
            route_wait(2),
            turn_left,
            route_wait(2),
            turn_down,
            route_wait(2),
            turn_right,
            route_wait(2),
            turn_left,
            route_wait(2),
            turn_down,
            route_wait(2),
          ),
          *move_route(
            character(5),
            turn_right,
            route_wait(2),
            turn_left,
            route_wait(2),
            turn_down,
            route_wait(2),
            turn_right,
            route_wait(2),
            turn_left,
            route_wait(2),
            turn_down,
            route_wait(2),
          ),
          wait_completion,
          control_variables(v(10), "-=", constant: 1),
          jump_label("Start"),
        ],
      ),
      stop_se,
      play_se(audio(name: "Elevator end", volume: 80)),
    ],
  ),
)