event(
  id: 11,
  name: "Nurse",
  x: 9,
  y: 7,
  page_0: page(
    graphic: graphic(
      name: "NPC 16",
    ),
    commands: [
      *comment(
        "This line of code sets the player's current position as ",
        "the spot they will return to after they lose a battle ",
        "and lack out.",
        "Page 2 of this event detects when this happens, and ",
        "heals the player's Pokémon and wishes them better ",
        "luck in future.",
      ),
      script("pbSetPokemonCenter"),
      text("\\rHello, and welcome to the Pokémon Center."),
      text("\\rWe restore your tired Pokémon to full health."),
      text("\\rWould you like to rest your Pokémon?"),
      *show_choices(
        choices: ["Yes", "No"],
        cancellation: 2,
        choice1: [
          text("\\rOK, I'll take your Pokémon for a few seconds."),
          script("$stats.poke_center_count += 1"),
          recover_all(0),
          comment("Nurse turns to face the healing machine."),
          *move_route(
            this,
            turn_left,
            route_wait(2),
          ),
          wait_completion,
          *comment(
            "Nurse places Poké Balls on the healing machine one at ",
            "a time.",
          ),
          control_variables(v(1), property: :party_members),
          control_variables(v(6), constant: 0),
          label("Place ball"),
          control_variables(v(6), "+=", constant: 1),
          play_se(audio(name: "Battle ball shake", volume: 80)),
          wait(8),
          *condition(
            variable: v(6),
            operation: "<",
            other_variable: v(1),
            then: [
              jump_label("Place ball"),
            ],
          ),
          comment("Healing animation and ME jingle."),
          *move_route(
            character(10),
            step_anime_on,
          ),
          play_me(audio(name: "Pkmn healing")),
          wait(58),
          *comment(
            "Poké Balls are removed from healing machine, nurse ",
            "turns to face the player.",
          ),
          control_variables(v(6), constant: 0),
          script("get_character(10).pattern = 0"),
          *move_route(
            character(10),
            step_anime_off,
          ),
          *move_route(
            this,
            route_wait(15),
            turn_down,
          ),
          wait_completion,
          comment("Pokérus check."),
          *condition(
            script: "pbPokerus?",
            then: [
              text("\\rYour Pokémon may be infected by Pokérus."),
              *text(
                "\\rLittle is known about the Pokérus except that they ",
                "are microscopic life-forms that attach to Pokémon.",
              ),
              *text(
                "\\rWhile infected, Pokémon are said to grow ",
                "exceptionally well.",
              ),
              control_switches(s(2), :ON),
            ],
            else: [
              text("\\rThank you for waiting."),
              text("\\rWe've restored your Pokémon to full health."),
              comment("Nurse bows."),
              *move_route(
                this,
                change_graphic(name: "NPC 16", pattern: 1),
                route_wait(10),
                change_graphic(name: "NPC 16"),
              ),
              wait_completion,
              text("\\rWe hope to see you again!"),
            ],
          ),
        ],
        choice2: [
          text("\\rWe hope to see you again!"),
        ],
      ),
    ],
  ),
  page_1: page(
    switch1: s(1),
    graphic: graphic(
      name: "NPC 16",
    ),
    trigger: :autorun,
    commands: [
      *comment(
        "Every map you can end up in after having all your ",
        "Pokémon faint (typically Poké Centers and home) ",
        "must have an Autorun event in it like this one.",
        "This event fully heals all the player's Pokémon, says ",
        "something to that effect, and turns the \"Starting ",
        "over\" switch OFF again.",
      ),
      *comment(
        "For convenience, this can be a single page in an ",
        "NPC's event (e.g. Mom, a nurse).",
      ),
      *text(
        "\\rFirst, you should restore your Pokémon to full ",
        "health.",
      ),
      script("$stats.poke_center_count += 1"),
      recover_all(0),
      comment("Nurse turns to face the healing machine."),
      *move_route(
        this,
        turn_left,
        route_wait(2),
      ),
      wait_completion,
      *comment(
        "Nurse places Poké Balls on the healing machine one at ",
        "a time.",
      ),
      control_variables(v(1), property: :party_members),
      control_variables(v(6), constant: 0),
      label("Place ball"),
      control_variables(v(6), "+=", constant: 1),
      play_se(audio(name: "Battle ball shake", volume: 80)),
      wait(8),
      *condition(
        variable: v(6),
        operation: "<",
        other_variable: v(1),
        then: [
          jump_label("Place ball"),
        ],
      ),
      comment("Healing animation and ME jingle."),
      *move_route(
        character(10),
        step_anime_on,
      ),
      play_me(audio(name: "Pkmn healing")),
      wait(58),
      *comment(
        "Poké Balls are removed from healing machine, nurse ",
        "turns to face the player.",
      ),
      control_variables(v(6), constant: 0),
      script("get_character(10).pattern = 0"),
      *move_route(
        character(10),
        step_anime_off,
      ),
      *move_route(
        this,
        route_wait(15),
        turn_down,
      ),
      wait_completion,
      text("\\rYour Pokémon have been healed to perfect health."),
      comment("Nurse bows."),
      *move_route(
        this,
        change_graphic(name: "NPC 16", pattern: 1),
        route_wait(10),
        change_graphic(name: "NPC 16"),
      ),
      wait_completion,
      text("\\rWe hope you excel!"),
      control_switches(s(1), :OFF),
    ],
  ),
)